### ISSUE TITLE
Display notice in module setting screen if sync failed order is there. and give button to trigger order sync

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/knawat-dropshipping-opencart#15]

**Comment by ElGreetly** [comment]
not working as expected 
![screenshot from 2019-02-11 16-59-55](https://user-images.githubusercontent.com/38695215/52568027-b90c5300-2e1e-11e9-9403-2279b156b284.png)

![screenshot from 2019-02-11 16-59-47](https://user-images.githubusercontent.com/38695215/52568016-b14cae80-2e1e-11e9-9c00-508721d04cf1.png)

**Comment by jayjittv** [comment]
Hello @ElGreetly ,

I have fixed this.

**Comment by ElGreetly** [comment]
check it on http://greetly.dev123.knawat.io still not syncing
